export const patientList = [
  {
    id: 1,
    name: "All",
    contents: [
      {
        patientId: "p001",
        firstName: "Liam",
        lastName: "lastname1",
        status: "unassigned",
        assignedTo: null,
        caseId: "0001",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p002",
        firstName: "Olivia",
        lastName: "lastname2",
        status: "active",
        assignedTo: "Ploy",
        caseId: "0002",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p003",
        firstName: "Noah",
        lastName: "lastname3",
        status: "active",
        assignedTo: "Four",
        caseId: "0003",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p004",
        firstName: "Emma",
        lastName: "lastname4",
        status: "completed",
        assignedTo: "Ploy",
        caseId: "0004",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p005",
        firstName: "Oliver",
        lastName: "lastname5",
        status: "unassigned",
        assignedTo: "have not assign yet",
        caseId: "0005",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p006",
        firstName: "Theodore",
        lastName: "lastname6",
        status: "unassigned",
        assignedTo: "have not assign yet",
        caseId: "0006",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p007",
        firstName: "Charlotte",
        lastName: "lastname7",
        status: "unassigned",
        assignedTo: "have not assign yet",
        caseId: "0007",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
    ],
  },
  {
    id: 2,
    name: "Unassigned",
    contents: [
      {
        patientId: "p001",
        firstName: "Liam",
        lastName: "lastname1",
        status: "unassigned",
        assignedTo: null,
        caseId: "0001",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },

      {
        patientId: "p005",
        firstName: "Oliver",
        lastName: "lastname5",
        status: "unassigned",
        assignedTo: "have not assign yet",
        caseId: "0005",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p006",
        firstName: "Theodore",
        lastName: "lastname6",
        status: "unassigned",
        assignedTo: "have not assign yet",
        caseId: "0006",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p007",
        firstName: "Charlotte",
        lastName: "lastname7",
        status: "unassigned",
        assignedTo: "have not assign yet",
        caseId: "0007",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
    ],
  },
  {
    id: 3,
    name: "Active",
    contents: [
      {
        patientId: "p002",
        firstName: "Olivia",
        lastName: "lastname2",
        status: "active",
        assignedTo: "Ploy",
        caseId: "0002",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
      {
        patientId: "p003",
        firstName: "Noah",
        lastName: "lastname3",
        status: "active",
        assignedTo: "Four",
        caseId: "0003",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
    ],
  },
  {
    id: 4,
    name: "Completed",
    contents: [
      {
        patientId: "p004",
        firstName: "Emma",
        lastName: "lastname4",
        status: "completed",
        assignedTo: "Ploy",
        caseId: "0004",
        intakeTimestamp: "10 Oct, 2222",
        referalNote: "Referal note of each patient",
      },
    ],
  },
];

export const rightMenuItem = [
  { id: 1, name: "View" },
  { id: 2, name: "Add new Patient" },
];
